In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
ann = tf.keras.models.Sequential()

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5575 - loss: 0.7085
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8034 - loss: 0.4482
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8095 - loss: 0.4313
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8099 - loss: 0.4220
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8178 - loss: 0.4104
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8352 - loss: 0.3790
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8437 - loss: 0.3747
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8375 - loss: 0.3806
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8385 - loss: 0.3774
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8530 - loss: 0.3583
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8485 - loss: 0.3623
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [14]:
for layer in ann.layers:
    weights = layer.get_weights()
    if weights:
        print(f"Layer: {layer.name}")
        print(f"Weights: {weights[0]}")
        print(f"Biases: {weights[1]}")

Layer: dense
Weights: [[-0.0427307  -0.12443867  0.06685825 -0.11391801 -0.04219904  0.33594862]
 [ 0.01036613 -0.06214793  0.37111706 -0.47253492  0.1957527   0.27379844]
 [ 0.06677718  0.10041832  0.06363187 -0.2898108  -0.20210359  0.22817677]
 [ 0.08906687 -0.00609235  0.0619691  -0.15161005  0.24076298  0.10433094]
 [-0.14583038  0.10166068 -0.10239603  0.37679505  0.1085477   0.0488767 ]
 [-0.13359988  0.37010112 -0.181602   -0.03050538  0.9057492  -0.9002161 ]
 [-0.0050819   0.11696225 -0.00640537 -0.30266172 -0.26663896 -0.02858102]
 [ 0.3234705  -0.5694254  -0.1946597  -0.4042832   0.22192344  0.0353195 ]
 [ 1.3298079   0.00899187 -1.1765081  -0.32546774 -0.23101398 -0.04023476]
 [ 0.03196834 -0.06975089  0.02317867 -0.2517945   0.25431424  0.03761878]
 [-0.17042933  1.0388528  -0.21450296 -0.95777863 -0.13655236 -0.37124908]
 [ 0.0424771  -0.02487631  0.05003754  0.08928005  0.21386355  0.07210725]]
Biases: [-0.33961403  0.9244521   0.28572875  0.49938223 -0.7038684   1.26648

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 198  207]]


0.858